from datetime import datetime, timedelta, timezone

from auth.user_entity import User, UserRole


class UserSeed:
    def __call__(self) -> list[User]:
        now = datetime.now(timezone.utc)

        def ts(days_ago: int = 0, hours_ago: int = 0) -> datetime:
            return now - timedelta(days=days_ago, hours=hours_ago)

        return [
            User(
                id=1,
                email="admin@example.com",
                username="admin",
                password_hash="!seed-admin",
                role=UserRole.ADMIN,
                avatar_url="https://cdn.example.com/avatars/admin.png",
                bio="Platform administrator",
                is_banned=False,
                created_at=ts(days_ago=365),
                updated_at=ts(days_ago=1),
                last_login_at=ts(hours_ago=2),
                email_verified_at=ts(days_ago=365),
                last_password_change=ts(days_ago=30),
            ),
            User(
                id=2,
                email="moderator@example.com",
                username="moderator",
                password_hash="!seed-moderator",
                role=UserRole.MODERATOR,
                avatar_url="https://cdn.example.com/avatars/mod.png",
                bio="Content moderator",
                is_banned=False,
                created_at=ts(days_ago=300),
                updated_at=ts(days_ago=3),
                last_login_at=ts(hours_ago=8),
                email_verified_at=ts(days_ago=300),
                last_password_change=ts(days_ago=45),
            ),
            User(
                id=3,
                email="alice@example.com",
                username="alice",
                password_hash="!seed-alice",
                role=UserRole.USER,
                avatar_url="https://cdn.example.com/avatars/alice.png",
                bio="Backend dev, loves Go and cats",
                is_banned=False,
                created_at=ts(days_ago=200),
                updated_at=ts(days_ago=5),
                last_login_at=ts(hours_ago=12),
                email_verified_at=ts(days_ago=200),
                last_password_change=ts(days_ago=60),
            ),
            User(
                id=4,
                email="bob@example.com",
                username="bob",
                password_hash="!seed-bob",
                role=UserRole.USER,
                avatar_url="https://cdn.example.com/avatars/bob.png",
                bio="Frontend enjoyer",
                is_banned=False,
                created_at=ts(days_ago=180),
                updated_at=ts(days_ago=2),
                last_login_at=ts(hours_ago=24),
                email_verified_at=ts(days_ago=180),
                last_password_change=ts(days_ago=20),
            ),
            User(
                id=5,
                email="carol@example.com",
                username="carol",
                password_hash="!seed-carol",
                role=UserRole.USER,
                avatar_url=None,
                bio=None,
                is_banned=False,
                created_at=ts(days_ago=150),
                updated_at=ts(days_ago=10),
                last_login_at=ts(days_ago=3),
                email_verified_at=ts(days_ago=150),
                last_password_change=ts(days_ago=90),
            ),
            User(
                id=6,
                email="dave@example.com",
                username="dave",
                password_hash="!seed-dave",
                role=UserRole.USER,
                avatar_url="https://cdn.example.com/avatars/dave.png",
                bio="QA engineer",
                is_banned=False,
                created_at=ts(days_ago=120),
                updated_at=ts(days_ago=7),
                last_login_at=ts(days_ago=1),
                email_verified_at=ts(days_ago=120),
                last_password_change=ts(days_ago=15),
            ),
            User(
                id=7,
                email="erin@example.com",
                username="erin",
                password_hash="!seed-erin",
                role=UserRole.USER,
                avatar_url="https://cdn.example.com/avatars/erin.png",
                bio="Data analyst",
                is_banned=False,
                created_at=ts(days_ago=90),
                updated_at=ts(days_ago=4),
                last_login_at=ts(days_ago=2),
                email_verified_at=ts(days_ago=90),
                last_password_change=ts(days_ago=10),
            ),
            User(
                id=8,
                email="frank@example.com",
                username="frank",
                password_hash="!seed-frank",
                role=UserRole.USER,
                avatar_url=None,
                bio="Lurker",
                is_banned=True,
                created_at=ts(days_ago=60),
                updated_at=ts(days_ago=1),
                last_login_at=ts(days_ago=20),
                email_verified_at=ts(days_ago=60),
                last_password_change=ts(days_ago=60),
            ),
            User(
                id=9,
                email=None,  # зарегистрирован без email
                username="grace",
                password_hash="!seed-grace",
                role=UserRole.USER,
                avatar_url="https://cdn.example.com/avatars/grace.png",
                bio="New here",
                is_banned=False,
                created_at=ts(days_ago=30),
                updated_at=ts(days_ago=30),
                last_login_at=None,  # ни разу не логинилась
                email_verified_at=None,
                last_password_change=ts(days_ago=30),
            ),
            User(
                id=10,
                email="henry@example.com",
                username="henry",
                password_hash="!seed-henry",
                role=UserRole.USER,
                avatar_url="https://cdn.example.com/avatars/henry.png",
                bio="",
                is_banned=False,
                created_at=ts(days_ago=7),
                updated_at=ts(days_ago=1),
                last_login_at=ts(hours_ago=6),
                email_verified_at=None,  # ещё не подтвердил
                last_password_change=ts(days_ago=7),
            ),
        ]
